# Generated by Django 5.1.6 on 2025-02-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
